- name: variables from arguments
  hosts: local
  connection: local
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Hi {{ Name }}, good morning"  #passing arguments from command line 