- name: install packages
  hosts: local
  connection: local
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loops: # list of map
    - { name: "mysql", state: "absent"}  # maps/dictonaries
    - { name: "nginx", state: "present"}
    - { name: "zip", state: "present"}  